Updated hardhat template to be compatible and tests running using fhevmjs 0.3.0 and fhevm 0.3.0
zama-ai/fhevm-hardhat-template pull request #8
Opened 2024-01-17 18:18 UTC by jatZama

2024-01-17 19:48 UTC, immortal-tofu requested changes

2024-01-17 19:48 UTC, immortal-tofu commented on hardhat.config.ts
> +    src: './examples',
We keep "contracts" for the template

2024-01-17 19:48 UTC, immortal-tofu commented on package.json
> +    "fhevm:start": "docker run -i -p 8545:8545 --rm --name fhevm ghcr.io/zama-ai/ethermint-dev-node:v0.2.3",
We need the 8546:8546 for websocket

2024-01-17 19:48 UTC, immortal-tofu commented on tasks/deployERC20.ts
Why deleting this file? It's here as an example

2024-01-17 19:48 UTC, immortal-tofu commented on tasks/mint.ts
Same

2024-01-17 19:48 UTC, immortal-tofu commented on test/confidentialToken/confidentialToken.ts
> +import { createInstances } from "fhevm/test/instance";
Keep `../signers`. This files are not published in the `fhevm` package. fhevm is basically a Solidity package with only the Solidity lib and Solidity mock.

2024-01-17 19:48 UTC, immortal-tofu commented on test/utils.ts
To restore

2024-01-17 19:48 UTC, immortal-tofu commented on test/types.ts
to restore

2024-01-17 19:48 UTC, immortal-tofu commented on test/signers.ts
to restore

2024-01-17 19:48 UTC, immortal-tofu commented on test/instance.ts
to restore

2024-01-17 19:48 UTC, immortal-tofu commented on test/confidentialToken/confidentialToken.ts
> +      this.signers.bob.signer.address,
Can't we reduce with `this.signers.bob` event with NonceManager?

2024-01-17 19:56 UTC, jatZama commented on package.json
> +    "fhevm:start": "docker run -i -p 8545:8545 --rm --name fhevm ghcr.io/zama-ai/ethermint-dev-node:v0.2.3",
Do we need also this in fhevm? Currently this is the same line used in fhevm fyi

2024-01-17 19:56 UTC, jatZama commented on tasks/deployERC20.ts
This was causing a conflict but I think it was because of the way utility functions were imported from fhevm (importing ethers in instance would cause hardhat to break at initialization)

2024-01-17 19:56 UTC, jatZama commented on test/confidentialToken/confidentialToken.ts
> +      this.signers.bob.signer.address,
no, this was necessary , because i imported the object from fhevm, but i believe this will become unecessary again if i restore the utility functions in typescript in this repo

2024-01-17 20:04 UTC, immortal-tofu commented on package.json
> +    "fhevm:start": "docker run -i -p 8545:8545 --rm --name fhevm ghcr.io/zama-ai/ethermint-dev-node:v0.2.3",
We don't use websocket in fhevm, so I think we don't need it. But for users developing contract and dapp, it can be useful!

2024-01-17 20:05 UTC, immortal-tofu commented on tasks/deployERC20.ts
I'd suggest to restore it as an example? Easy to modify if developers want to use it for their own contract.

2024-01-17 20:08 UTC, immortal-tofu commented on test/confidentialToken/confidentialToken.ts
> +      this.signers.bob.signer.address,
I mean we could have this in signers:

```
      signers = {
        alice: new NonceManager(eSigners[0]).signer,
        bob: new NonceManager(eSigners[1]).signer,
        carol: new NonceManager(eSigners[2]).signer,
        dave: new NonceManager(eSigners[3]).signer,
        eve: new NonceManager(eSigners[4]).signer,
      };
```
It would simplify a lot the process. It needs to be tested, but I guess it's fine.

2024-01-17 20:35 UTC, jatZama commented on test/confidentialToken/confidentialToken.ts
> +      this.signers.bob.signer.address,
to be honest i feel this will break the advantage of using a NonceManager when sending transaction, but to be tested later.

2024-01-18 11:18 UTC, immortal-tofu approved these changes
Seems good! Just be sure it's working with [fhevm@0.3.0](https://www.npmjs.com/package/fhevm)

2024-01-18 13:28 UTC, closed without merging